### PR TITLE
Json fe bump

### PR DESCRIPTION
**Pull request by NikitaPoly**
bumped version of FE to match s3

### CODE REVIEW

**Comment by luciipak** [comment]
the version wasn't changed

**Comment by NikitaPoly** [comment]
@luciipak  I added the change to the json, do I need to make it in a different file?

**Comment by luciipak** [comment]
the diff only shows the package-lock.json was changed? should be in the package.json

**Comment by tannermpeterson** [comment]
You change the version package.json, then run you can run `npm i` to updated package-lock.json. You shouldn't ever edit package-lock.json manually

**Review by luciipak — APPROVED** [review]

**Pull request merged**
